import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

/// Central Firebase startup controller.
///
/// Mobile Firebase is initialized from the native configuration generated by
/// google-services.json / GoogleService-Info.plist. This avoids depending on a
/// hand-copied FirebaseOptions value at Android startup.
class FirebaseBootstrap {
  FirebaseBootstrap._();
  static final FirebaseBootstrap instance = FirebaseBootstrap._();

  final ValueNotifier<bool> ready = ValueNotifier<bool>(Firebase.apps.isNotEmpty);
  final ValueNotifier<String?> error = ValueNotifier<String?>(null);
  bool _started = false;
  Future<void>? _running;

  Future<void> start() {
    if (ready.value || Firebase.apps.isNotEmpty) {
      ready.value = true;
      return Future<void>.value();
    }
    return _running ??= _startLoop();
  }

  Future<void> _startLoop() async {
    if (_started) return;
    _started = true;

    while (Firebase.apps.isEmpty) {
      try {
        // On Android/iOS let the native Firebase configuration be the source
        // of truth. google-services.json and GoogleService-Info.plist are
        // already part of the project.
        await Firebase.initializeApp();
        ready.value = Firebase.apps.isNotEmpty;
        error.value = null;
        if (ready.value) return;
      } catch (e) {
        error.value = e.toString();
      }

      // Retry indefinitely. A temporary Firebase/network delay must never be
      // converted into a fake "internet problem" and must never stop startup.
      await Future<void>.delayed(const Duration(seconds: 3));
    }

    ready.value = true;
  }

  /// Waits for Firebase to become ready. The timeout only controls how long
  /// the caller waits; it does NOT stop Firebase's background retry loop.
  Future<bool> waitUntilReady({Duration timeout = const Duration(seconds: 30)}) async {
    if (ready.value || Firebase.apps.isNotEmpty) {
      ready.value = true;
      return true;
    }

    await start();
    if (ready.value || Firebase.apps.isNotEmpty) return true;

    final completer = Completer<bool>();
    Timer? timer;

    void listener() {
      if (ready.value || Firebase.apps.isNotEmpty) {
        if (!completer.isCompleted) completer.complete(true);
      }
    }

    ready.addListener(listener);
    timer = Timer(timeout, () {
      if (!completer.isCompleted) completer.complete(false);
    });

    final result = await completer.future;
    ready.removeListener(listener);
    timer.cancel();
    return result;
  }

  String get lastError => error.value ?? '';

  void dispose() {
    ready.dispose();
    error.dispose();
  }
}
