import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:http/http.dart' as http;
import '../services/admin_service.dart';
import '../services/r2_worker_service.dart';

class AdminControlCenterScreen extends StatefulWidget { const AdminControlCenterScreen({super.key}); @override State<AdminControlCenterScreen> createState()=>_AdminControlCenterScreenState(); }
class _AdminControlCenterScreenState extends State<AdminControlCenterScreen>{
 int tab=0; final db=FirebaseFirestore.instance; final fn=FirebaseFunctions.instanceFor(region:'us-central1'); bool uploading=false;
 Future<void> _ban(String uid) async { final r=TextEditingController(); int days=7; final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('حظر المستخدم'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:r,decoration:const InputDecoration(labelText:'سبب الحظر')),TextField(decoration:const InputDecoration(labelText:'عدد الأيام'),keyboardType:TextInputType.number,onChanged:(v)=>days=int.tryParse(v)??7)]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('حظر'))])); if(ok==true&&r.text.trim().isNotEmpty){await fn.httpsCallable('setUserBan').call({'uid':uid,'reason':r.text.trim(),'days':days});}}
 Future<String?> _pickNotificationImage() async { final x=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:82,maxWidth:1600); if(x==null)return null; setState(()=>uploading=true); try{final bytes=await File(x.path).readAsBytes(); final key='notifications/${DateTime.now().millisecondsSinceEpoch}_${x.name.replaceAll(RegExp(r'[^a-zA-Z0-9._-]'),'_')}'; final res=await http.put(Uri.parse(R2WorkerService.keyToUrl(key)),headers:{'Content-Type':'image/jpeg'},body:bytes); if(res.statusCode>=200&&res.statusCode<300)return R2WorkerService.keyToUrl(key); throw Exception('R2 upload ${res.statusCode}');}finally{if(mounted)setState(()=>uploading=false);}}
 Future<void> _notify() async { final title=TextEditingController(),body=TextEditingController(),campaign=TextEditingController(),description=TextEditingController(); String imageUrl=''; DateTime when=DateTime.now().add(const Duration(minutes:5)); final ok=await showDialog<bool>(context:context,builder:(_)=>StatefulBuilder(builder:(ctx,setLocal)=>AlertDialog(title:const Text('إشعار مجدول'),content:SingleChildScrollView(child:Column(children:[TextField(controller:title,decoration:const InputDecoration(labelText:'العنوان')),TextField(controller:body,decoration:const InputDecoration(labelText:'الرسالة')),const SizedBox(height:8),OutlinedButton.icon(onPressed:uploading?null:()async{final u=await _pickNotificationImage();if(u!=null){imageUrl=u;setLocal((){});}},icon:const Icon(Icons.image),label:Text(imageUrl.isEmpty?'رفع صورة من الهاتف':'تم رفع الصورة ✓')),if(imageUrl.isNotEmpty)Padding(padding:const EdgeInsets.all(8),child:Image.network(imageUrl,height:80,fit:BoxFit.cover)),TextField(controller:campaign,decoration:const InputDecoration(labelText:'اسم الحملة')),TextField(controller:description,decoration:const InputDecoration(labelText:'الوصف')),ListTile(title:Text('وقت الإرسال: ${when.toLocal()}'),trailing:const Icon(Icons.schedule),onTap:()async{final d=await showDatePicker(context:ctx,initialDate:when,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)));if(d==null)return;final t=await showTimePicker(context:ctx,initialTime:TimeOfDay.fromDateTime(when));if(t!=null){when=DateTime(d.year,d.month,d.day,t.hour,t.minute);setLocal((){});}})])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('جدولة'))])); if(ok==true&&title.text.trim().isNotEmpty&&body.text.trim().isNotEmpty){await fn.httpsCallable('scheduleNotification').call({'title':title.text.trim(),'body':body.text.trim(),'imageUrl':imageUrl,'campaign':campaign.text.trim(),'description':description.text.trim(),'sendAt':when.toUtc().toIso8601String(),'audience':'all'});}}
 Future<void> _admin() async {final e=TextEditingController(),p=TextEditingController(),n=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('إضافة حساب أدمن'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'الاسم')),TextField(controller:e,decoration:const InputDecoration(labelText:'البريد')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('إنشاء'))]));if(ok==true)await fn.httpsCallable('createAdminAccount').call({'email':e.text.trim(),'password':p.text,'name':n.text.trim()});}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('مركز الاعتماد الموحد')),body:Column(children:[SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[_tab('المحاضرات',0),_tab('مراجعة الكورسات',1),_tab('المفهّمين',2),_tab('المستخدمون',3),_tab('الإشعارات',4),_tab('حسابات الأدمن',5)])),Expanded(child:[_meetings(),_courses(),_mufahems(),_users(),_notifications(),_admins()][tab])]));
 Widget _tab(String t,int i)=>Padding(padding:const EdgeInsets.all(6),child:ChoiceChip(label:Text(t),selected:tab==i,onSelected:(_){setState(()=>tab=i);}));
 Widget _meetings()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('istifhams').where('status',whereIn:['paid','completed']).snapshots(),builder:(c,s)=>ListView(children:(s.data?.docs??[]).map((d){final x=d.data();final rec=(x['recordingUrl']??x['recordingR2Url']??'').toString();return ListTile(leading:const Icon(Icons.video_call),title:Text((x['title']??'محاضرة').toString()),subtitle:Text('${x['meetingTime']??'غير محدد'}'),trailing:rec.isEmpty?const Text('لا يوجد تسجيل'):IconButton(icon:const Icon(Icons.play_circle),onPressed:()=>showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('مراجعة فيديو المحاضرة'),content:Text(rec),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('إغلاق'))])));}).toList()));
 Widget _courses()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('courses').where('status',isEqualTo:'pending').snapshots(),builder:(c,s)=>ListView(children:(s.data?.docs??[]).map((d)=>ListTile(title:Text((d.data()['title']??'بدون اسم').toString()),trailing:Wrap(children:[IconButton(icon:const Icon(Icons.check),onPressed:()=>AdminService().reviewCourse(courseId:d.id,decision:'approved')),IconButton(icon:const Icon(Icons.close),onPressed:()async{final r=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('سبب الرفض'),content:TextField(controller:r),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('رفض'))]));if(ok==true&&r.text.trim().isNotEmpty)await AdminService().reviewCourse(courseId:d.id,decision:'rejected',rejectionReason:r.text.trim());})])).toList()));
 Widget _mufahems()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('users').where('mode',isEqualTo:'mofahhem').limit(200).snapshots(),builder:(c,s)=>ListView(children:(s.data?.docs??[]).map((d){final x=d.data();return ListTile(title:Text((x['name']??x['email']??d.id).toString()),subtitle:Text('${x['email']??''}'),trailing:IconButton(icon:const Icon(Icons.block),onPressed:()=>_ban(d.id)));}).toList()));
 Widget _users()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('users').limit(200).snapshots(),builder:(c,s)=>ListView(children:(s.data?.docs??[]).map((d)=>ListTile(title:Text((d.data()['name']??d.data()['email']??d.id).toString()),subtitle:Text('${d.data()['email']??''}'),trailing:IconButton(icon:const Icon(Icons.block),onPressed:()=>_ban(d.id))).toList()));
 Widget _notifications()=>Center(child:FilledButton.icon(onPressed:_notify,icon:const Icon(Icons.notifications_active),label:const Text('إرسال / جدولة إشعار مع رفع صورة')));
 Widget _admins()=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('users').where('isAdmin',isEqualTo:true).snapshots(),builder:(c,s)=>ListView(padding:const EdgeInsets.all(12),children:[FilledButton.icon(onPressed:_admin,icon:const Icon(Icons.person_add),label:const Text('إضافة أدمن')),const SizedBox(height:12),...(s.data?.docs??[]).map((d){final x=d.data();return Card(child:ListTile(leading:const Icon(Icons.admin_panel_settings),title:Text((x['name']??'بدون اسم').toString()),subtitle:Text((x['email']??d.id).toString()),trailing:Text(x['role']?.toString()??'admin')));})]));
}
